jwt:
  key: 25cf3c44c8f39313e8cbf7c23e22fe8b2ee8b288ee5206b0a6397583a1f7f0ef
#  key: ${JWT_KEY:JUJUTSU_KAISEN_SHIBUYA_ARC_ITADORI_YUJI}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
#  expired-token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJlbWFpbC0xQGdtYWlsLmNvbSIsImlhdCI6MTcyNzQ1Mjk2MCwiZXhwIjoxNzI3NDU2NTYwfQ.oP0dNWn75v8Ka7fvxt-966ug2q3A5i4Ef-urjo0bQtSCZeq9f4ijA7HydBC-xMX2

hibernate:
  id:
    new_generator_mappings: true
